name: "Rust Licenses Noticer"
description: >
  Retrieves dependency metadata of your Rust project with `cargo-deny`,
  generates a `THIRD_PARTY_NOTICES.md` file from a provided template and
  compares it with yours, failing if they are not the same.
inputs:
  project-root:
    description: "The root directory of the project to check"
    required: false
    default: ${{ github.workspace }}
  template-file:
    description: "The path to the template file to use"
    required: true
  notices-file:
    description: "The path to the notices file"
    required: false
    default: "./THIRD_PARTY_NOTICES.md"
  rust-licenses-noticer-branch:
    description: "The branch to use for the rust-licenses-noticer tool"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Run the default program
      run: >
        nix run .# --
        --cargo-root=${{ inputs.project-root }}
        --output-file=${{ inputs.notices-file }}
        --template-file=${{ inputs.template-file }}
      shell: bash
