[package]
name = "rust-licenses-noticer"
version = "0.1.0"
authors = ["The New Relic Agent Control Team"]
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
lazy_static = "1.5.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tera = "1.20.0"
