name: ⏯️ Generate pre-release PR

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prerelease:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_create_prerelease_pr.yml@ea1a94a32334bbca45528ebddb5aa1d4f7c37e5f # main
    with:
      cargo_toml_path: "Cargo.toml"
    secrets:
      app_id: ${{ secrets.AGENT_CONTROL_APP_ID }}
      app_private_key: ${{ secrets.AGENT_CONTROL_APP_PKEY }}
