name: ⏯️ Generate pre-release PR

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prerelease:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_create_prerelease_pr.yml@d8d1f6760353f19d93f86573b32599b7ebf51af0 # main
    with:
      cargo_toml_path: "Cargo.toml"
    secrets:
      app_id: ${{ secrets.AGENT_CONTROL_APP_ID }}
      app_private_key: ${{ secrets.AGENT_CONTROL_APP_PKEY }}
