name: validates changelog

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: read

jobs:
  check-changelog:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_check_changelog.yml@b9b9b83f7d4b6203e3b03bf01524fdfc26cdef12 # main
