name: validates changelog

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: read

jobs:
  check-changelog:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_check_changelog.yml@a96b1b58f71ee5b3acb41d22b4ea33bddbbe2954 # main
