name: validates changelog

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: read

jobs:
  check-changelog:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_check_changelog.yml@ea1a94a32334bbca45528ebddb5aa1d4f7c37e5f # main
