permissions:
  contents: read
on:
  push:

# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Tests
jobs:
  basic-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets

  cargo-fmt:
    runs-on: ubuntu-latest
    name: Format test / stable
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --check

  cargo-clippy:
    runs-on: ubuntu-latest
    name: clippy / ${{ matrix.toolchain }}
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy -- -D clippy::all

  third-party-notices-check:
    name: ⚖️ Third party licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: newrelic/rust-licenses-noticer@v1
        with:
          template-file: THIRD_PARTY_NOTICES.md.tmpl

  check-all-green:
    name: 🟢 All required checks and tests pass
    if: always()

    needs:
      - basic-tests
      - cargo-fmt
      - cargo-clippy
      - third-party-notices-check

    runs-on: Ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}